GET http://localhost:3000/api/v1/users
###

GET http://localhost:3000/api/v1/users/3
###

POST http://localhost:3000/api/v1/users/
Content-Type: application/json

{
  "uuid": "111d",
  "name": "Brahyan",
  "last_name": "Cueva",
  "email": "bcueva@gmail.com",
  "password": "pass1234"
}