GET http://localhost:3000/api/v1/products?category=para-el
###

GET http://localhost:3000/api/v1/products/taza-3d-hombre-arana
###
POST http://localhost:3000/api/v1/products
Content-Type: application/json

{
  "name": "Laptop Lenovo IdeaPad 3",
  "description": "Laptop con procesador AMD Ryzen 5, 8GB RAM, 256GB SSD",
  "price": "1899.90",
  "is_active": true
}